import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import { ProgressIndicator } from "@/components/ProgressIndicator/ProgessIndicator";

const inter = Inter({ subsets: ["latin"] });

type DownloadStatusTypes = "started" | "pending" | "stopped";

export default function Home() {
  const [downloadStatus, setDownloadStatus] =
    useState<DownloadStatusTypes>("pending");

  const downloadStatusTextMapping = {
    started: "Stop Download",
    pending: "Start Download",
    stopped: "Retrieve Download",
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.center}>
          <ProgressIndicator progress={20} />
          <div className={styles.buttonsContainer}>
            <button
              type="button"
              className={`${styles.downloadButton} ${styles.downloadButton}`}
            >
              {downloadStatusTextMapping[downloadStatus]}
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
